CREATE TABLE IF NOT EXISTS qt_alarm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL UNIQUE,
  days TEXT NOT NULL DEFAULT '[]',
  time TEXT NOT NULL DEFAULT '06:00',
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
